### ISSUE TITLE
not working after uprade to macOS Catalina

### ISSUE THREAD

**Issue by samuela** [samuela/remod#1]
```
❯ remod /etc/nuvemfs-dev.env
/usr/local/lib/node_modules/remod-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module '/usr/local/lib/node_modules/remod-cli/node_modules/userid/build/Debug/userid.node'
Require stack:
- /usr/local/lib/node_modules/remod-cli/node_modules/userid/lib/userid.js
- /usr/local/lib/node_modules/remod-cli/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/remod-cli/node_modules/userid/lib/userid.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/remod-cli/node_modules/userid/lib/userid.js',
    '/usr/local/lib/node_modules/remod-cli/dist/index.js'
  ]
}
```

**Comment by samuela** [comment]
Solved with
```bash
brew upgrade # I have npm/node installed via homebrew
npm install -g npm # upgrade npm
npm uninstall -g remod-cli
npm i -g remod-cli
```
